### ISSUE TITLE
Hot reloading of assets (e.g. yaml) doesn't work

### ISSUE THREAD

**Issue by entropitor** [facebook/metro-bundler#34] opened 2017-07-26 14:46 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When adding a file extension (e.g. yml) to getAssetExts and using hot reloading, it's not processed by the babel transform (e.g. `babel-plugin-convert-to-json`), instead it tries to parse it as js

**What is the expected behavior?**
The hot reloading of the file transforms the file using the babel transform, just like on first loading the file

**Comment by cpojer** [comment] 2017-10-09 09:58
cc @rafeca

**Comment by rafeca** [comment] 2017-10-16 07:08
@entropitor: Thanks for reporting! This seems to be the same issue as https://github.com/facebook/react-native/issues/7279

The fix has been included in React Native v0.49. Feel free to reopen this issue if you can still reproduce it on that version

**Closed by rafeca** 2017-10-16 07:08 UTC
